// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Hardcoded project defaults (publishable anon key — safe for browser).
// These act as a fallback if Vite env injection is not available at runtime
// (e.g. preview build cached before .env was restored).
const DEFAULT_SUPABASE_URL = 'https://akmoxsaihexwjijtjzsj.supabase.co';
const DEFAULT_SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrbW94c2FpaGV4d2ppanRqenNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc0NzQxNzgsImV4cCI6MjA5MzA1MDE3OH0.fM_CTaeeUgXtLFB4TXsTfzri6jvOLvTHaspOCmEhzMQ';

const ENV_URL = (import.meta.env.VITE_SUPABASE_URL as string | undefined)?.trim();
const ENV_KEY = (
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ||
  (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined)
)?.trim();

const SUPABASE_URL = ENV_URL || DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = ENV_KEY || DEFAULT_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (typeof window !== 'undefined') {
  // eslint-disable-next-line no-console
  console.info('[supabase] init', {
    urlSource: ENV_URL ? 'env' : 'fallback',
    keySource: ENV_KEY ? 'env' : 'fallback',
    url: SUPABASE_URL,
    keyLen: SUPABASE_PUBLISHABLE_KEY.length,
  });
}

const _client = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
export const supabase: any = _client;
